// <auto-generated />
using System;
using System.Collections.Generic;
using Cooklyn.Server.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cooklyn.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218030730_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cooklyn.Server.Domain.ItemCategoryMappings.ItemCategoryMapping", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("StoreSectionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("store_section_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Source", "Cooklyn.Server.Domain.ItemCategoryMappings.ItemCategoryMapping.Source#MappingSource", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("source");
                        });

                    b.HasKey("Id")
                        .HasName("pk_item_category_mappings");

                    b.HasIndex("StoreSectionId")
                        .HasDatabaseName("ix_item_category_mappings_store_section_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_item_category_mappings_tenant_id");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_item_category_mappings_tenant_id_normalized_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("item_category_mappings", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.ItemCollections.ItemCollection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_item_collections");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_item_collections_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_item_collections_tenant_id_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("item_collections", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.ItemCollections.ItemCollectionItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ItemCollectionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_collection_id");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("quantity");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("StoreSectionId")
                        .HasColumnType("text")
                        .HasColumnName("store_section_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Unit", "Cooklyn.Server.Domain.ItemCollections.ItemCollectionItem.Unit#IngredientUnit", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("unit");
                        });

                    b.HasKey("Id")
                        .HasName("pk_item_collection_items");

                    b.HasIndex("ItemCollectionId")
                        .HasDatabaseName("ix_item_collection_items_item_collection_id");

                    b.HasIndex("StoreSectionId")
                        .HasDatabaseName("ix_item_collection_items_store_section_id");

                    b.ToTable("item_collection_items", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Recipes.Ingredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("amount");

                    b.Property<string>("AmountText")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("amount_text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("CustomUnit")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("custom_unit");

                    b.Property<string>("GroupName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipe_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Unit", "Cooklyn.Server.Domain.Recipes.Ingredient.Unit#IngredientUnit", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("unit");
                        });

                    b.HasKey("Id")
                        .HasName("pk_ingredients");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_ingredients_recipe_id");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Recipes.NutritionInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal?>("AddedSugarsGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("added_sugars_grams");

                    b.Property<decimal?>("CalciumPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("calcium_percent");

                    b.Property<decimal?>("Calories")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("calories");

                    b.Property<decimal?>("CholesterolMilligrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cholesterol_milligrams");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<decimal?>("DietaryFiberGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("dietary_fiber_grams");

                    b.Property<decimal?>("IronPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("iron_percent");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsManuallyEntered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manually_entered");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<decimal?>("PotassiumPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("potassium_percent");

                    b.Property<decimal?>("ProteinGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("protein_grams");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipe_id");

                    b.Property<decimal?>("SaturatedFatGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("saturated_fat_grams");

                    b.Property<decimal?>("SodiumMilligrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sodium_milligrams");

                    b.Property<decimal?>("TotalCarbohydratesGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_carbohydrates_grams");

                    b.Property<decimal?>("TotalFatGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_fat_grams");

                    b.Property<decimal?>("TotalSugarsGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_sugars_grams");

                    b.Property<decimal?>("TransFatGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("trans_fat_grams");

                    b.Property<decimal?>("VitaminDPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("vitamin_d_percent");

                    b.HasKey("Id")
                        .HasName("pk_nutrition_infos");

                    b.HasIndex("RecipeId")
                        .IsUnique()
                        .HasDatabaseName("ix_nutrition_infos_recipe_id");

                    b.ToTable("nutrition_infos", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Recipes.Recipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageS3Bucket")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_s3bucket");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("Notes")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("notes");

                    b.Property<int?>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.Property<string>("Source")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source");

                    b.Property<string>("Steps")
                        .HasColumnType("text")
                        .HasColumnName("steps");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ImageS3Key", "Cooklyn.Server.Domain.Recipes.Recipe.ImageS3Key#BlobStorageKey", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("image_s3_key");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Rating", "Cooklyn.Server.Domain.Recipes.Recipe.Rating#Rating", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("rating");
                        });

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_recipes_tenant_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_recipes_title");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Recipes.RecipeFlagEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipe_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Flag", "Cooklyn.Server.Domain.Recipes.RecipeFlagEntry.Flag#RecipeFlag", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("flag");
                        });

                    b.HasKey("Id")
                        .HasName("pk_recipe_flag_entries");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_flag_entries_recipe_id");

                    b.ToTable("recipe_flag_entries", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Recipes.RecipeTag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipe_id");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag_id");

                    b.HasKey("Id")
                        .HasName("pk_recipe_tags");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_tags_recipe_id");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_recipe_tags_tag_id");

                    b.HasIndex("RecipeId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_tags_recipe_id_tag_id");

                    b.ToTable("recipe_tags", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.ShoppingLists.ShoppingList", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_on");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("StoreId")
                        .HasColumnType("text")
                        .HasColumnName("store_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Status", "Cooklyn.Server.Domain.ShoppingLists.ShoppingList.Status#ShoppingListStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("status");
                        });

                    b.HasKey("Id")
                        .HasName("pk_shopping_lists");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("ix_shopping_lists_store_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_shopping_lists_tenant_id");

                    b.ToTable("shopping_lists", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.ShoppingLists.ShoppingListItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CheckedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_on");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_checked");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("quantity");

                    b.Property<string>("ShoppingListId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shopping_list_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("StoreSectionId")
                        .HasColumnType("text")
                        .HasColumnName("store_section_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Unit", "Cooklyn.Server.Domain.ShoppingLists.ShoppingListItem.Unit#IngredientUnit", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("unit");
                        });

                    b.HasKey("Id")
                        .HasName("pk_shopping_list_items");

                    b.HasIndex("ShoppingListId")
                        .HasDatabaseName("ix_shopping_list_items_shopping_list_id");

                    b.HasIndex("StoreSectionId")
                        .HasDatabaseName("ix_shopping_list_items_store_section_id");

                    b.ToTable("shopping_list_items", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.ShoppingLists.ShoppingListItemRecipeSource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<decimal?>("OriginalQuantity")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("original_quantity");

                    b.Property<string>("OriginalUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("original_unit");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipe_id");

                    b.Property<string>("ShoppingListItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shopping_list_item_id");

                    b.HasKey("Id")
                        .HasName("pk_shopping_list_item_recipe_sources");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_shopping_list_item_recipe_sources_recipe_id");

                    b.HasIndex("ShoppingListItemId")
                        .HasDatabaseName("ix_shopping_list_item_recipe_sources_shopping_list_item_id");

                    b.HasIndex("ShoppingListItemId", "RecipeId")
                        .IsUnique()
                        .HasDatabaseName("ix_shopping_list_item_recipe_sources_shopping_list_item_id_rec");

                    b.ToTable("shopping_list_item_recipe_sources", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.StoreSections.StoreSection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_store_sections");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_store_sections_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_store_sections_tenant_id_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("store_sections", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Stores.Store", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_stores");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_stores_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_stores_tenant_id_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Stores.StoreAisle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("CustomName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("custom_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("store_id");

                    b.Property<string>("StoreSectionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("store_section_id");

                    b.HasKey("Id")
                        .HasName("pk_store_aisles");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("ix_store_aisles_store_id");

                    b.HasIndex("StoreSectionId")
                        .HasDatabaseName("ix_store_aisles_store_section_id");

                    b.HasIndex("StoreId", "StoreSectionId")
                        .IsUnique()
                        .HasDatabaseName("ix_store_aisles_store_id_store_section_id");

                    b.ToTable("store_aisles", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Stores.StoreDefaultCollection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ItemCollectionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_collection_id");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("store_id");

                    b.HasKey("Id")
                        .HasName("pk_store_default_collections");

                    b.HasIndex("ItemCollectionId")
                        .HasDatabaseName("ix_store_default_collections_item_collection_id");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("ix_store_default_collections_store_id");

                    b.HasIndex("StoreId", "ItemCollectionId")
                        .IsUnique()
                        .HasDatabaseName("ix_store_default_collections_store_id_item_collection_id")
                        .HasFilter("is_deleted = false");

                    b.ToTable("store_default_collections", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Tags.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tags_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_tenant_id_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Tenants.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_name");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("DefaultStoreId")
                        .HasColumnType("text")
                        .HasColumnName("default_store_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("identifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "Cooklyn.Server.Domain.Users.User.Email#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Role", "Cooklyn.Server.Domain.Users.User.Role#UserRole", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("role");
                        });

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DefaultStoreId")
                        .HasDatabaseName("ix_users_default_store_id");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identifier");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.HasIndex("Username")
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Users.UserPermission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Permission", "Cooklyn.Server.Domain.Users.UserPermission.Permission#Permission", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("permission");
                        });

                    b.HasKey("Id")
                        .HasName("pk_user_permissions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_permissions_user_id");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.ItemCategoryMappings.ItemCategoryMapping", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.StoreSections.StoreSection", null)
                        .WithMany()
                        .HasForeignKey("StoreSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_category_mappings_store_sections_store_section_id");

                    b.HasOne("Cooklyn.Server.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_category_mappings_tenants_tenant_id");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.ItemCollections.ItemCollection", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_collections_tenants_tenant_id");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.ItemCollections.ItemCollectionItem", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.ItemCollections.ItemCollection", null)
                        .WithMany("Items")
                        .HasForeignKey("ItemCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_collection_items_item_collections_item_collection_id");

                    b.HasOne("Cooklyn.Server.Domain.StoreSections.StoreSection", null)
                        .WithMany()
                        .HasForeignKey("StoreSectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_item_collection_items_store_sections_store_section_id");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Recipes.Ingredient", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.Recipes.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredients_recipes_recipe_id");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Recipes.NutritionInfo", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.Recipes.Recipe", null)
                        .WithOne("NutritionInfo")
                        .HasForeignKey("Cooklyn.Server.Domain.Recipes.NutritionInfo", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nutrition_infos_recipes_recipe_id");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Recipes.Recipe", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipes_tenants_tenant_id");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Recipes.RecipeFlagEntry", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.Recipes.Recipe", null)
                        .WithMany("Flags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_flag_entries_recipes_recipe_id");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Recipes.RecipeTag", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_tags_recipes_recipe_id");

                    b.HasOne("Cooklyn.Server.Domain.Tags.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_tags_tags_tag_id");

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.ShoppingLists.ShoppingList", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.Stores.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_shopping_lists_stores_store_id");

                    b.HasOne("Cooklyn.Server.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_lists_tenants_tenant_id");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.ShoppingLists.ShoppingListItem", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.ShoppingLists.ShoppingList", null)
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_list_items_shopping_lists_shopping_list_id");

                    b.HasOne("Cooklyn.Server.Domain.StoreSections.StoreSection", null)
                        .WithMany()
                        .HasForeignKey("StoreSectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_shopping_list_items_store_sections_store_section_id");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.ShoppingLists.ShoppingListItemRecipeSource", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_list_item_recipe_sources_recipes_recipe_id");

                    b.HasOne("Cooklyn.Server.Domain.ShoppingLists.ShoppingListItem", null)
                        .WithMany("RecipeSources")
                        .HasForeignKey("ShoppingListItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_list_item_recipe_sources_shopping_list_items_shopp");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.StoreSections.StoreSection", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_store_sections_tenants_tenant_id");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Stores.Store", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stores_tenants_tenant_id");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Stores.StoreAisle", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.Stores.Store", null)
                        .WithMany("StoreAisles")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_store_aisles_stores_store_id");

                    b.HasOne("Cooklyn.Server.Domain.StoreSections.StoreSection", null)
                        .WithMany()
                        .HasForeignKey("StoreSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_store_aisles_store_sections_store_section_id");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Stores.StoreDefaultCollection", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.ItemCollections.ItemCollection", "ItemCollection")
                        .WithMany()
                        .HasForeignKey("ItemCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_store_default_collections_item_collections_item_collection_");

                    b.HasOne("Cooklyn.Server.Domain.Stores.Store", null)
                        .WithMany("StoreDefaultCollections")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_store_default_collections_stores_store_id");

                    b.Navigation("ItemCollection");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Tags.Tag", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_tenants_tenant_id");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Users.User", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.Stores.Store", null)
                        .WithMany()
                        .HasForeignKey("DefaultStoreId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_stores_default_store_id");

                    b.HasOne("Cooklyn.Server.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Users.UserPermission", b =>
                {
                    b.HasOne("Cooklyn.Server.Domain.Users.User", null)
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_users_user_id");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.ItemCollections.ItemCollection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Recipes.Recipe", b =>
                {
                    b.Navigation("Flags");

                    b.Navigation("Ingredients");

                    b.Navigation("NutritionInfo");

                    b.Navigation("RecipeTags");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.ShoppingLists.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.ShoppingLists.ShoppingListItem", b =>
                {
                    b.Navigation("RecipeSources");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Stores.Store", b =>
                {
                    b.Navigation("StoreAisles");

                    b.Navigation("StoreDefaultCollections");
                });

            modelBuilder.Entity("Cooklyn.Server.Domain.Users.User", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
