namespace Cooklyn.Server.Services;

public static class ItemCategorySeedData
{
    /// <summary>
    /// Maps normalized item names to store section names.
    /// Multi-word entries (e.g. "peanut butter") exist for disambiguation.
    /// Dual-use herbs default to Produce.
    /// </summary>
    public static readonly Dictionary<string, string> Mappings = new(StringComparer.OrdinalIgnoreCase)
    {
        // ── Produce ──
        { "apple", "Produce" },
        { "apricot", "Produce" },
        { "artichoke", "Produce" },
        { "arugula", "Produce" },
        { "asparagus", "Produce" },
        { "avocado", "Produce" },
        { "banana", "Produce" },
        { "basil", "Produce" },
        { "bean sprout", "Produce" },
        { "beet", "Produce" },
        { "bell pepper", "Produce" },
        { "blackberry", "Produce" },
        { "blueberry", "Produce" },
        { "bok choy", "Produce" },
        { "broccoli", "Produce" },
        { "brussels sprout", "Produce" },
        { "butternut squash", "Produce" },
        { "cabbage", "Produce" },
        { "cantaloupe", "Produce" },
        { "carrot", "Produce" },
        { "cauliflower", "Produce" },
        { "celery", "Produce" },
        { "cherry", "Produce" },
        { "chive", "Produce" },
        { "cilantro", "Produce" },
        { "clementine", "Produce" },
        { "coconut", "Produce" },
        { "collard green", "Produce" },
        { "corn", "Produce" },
        { "cranberry", "Produce" },
        { "cucumber", "Produce" },
        { "date", "Produce" },
        { "dill", "Produce" },
        { "eggplant", "Produce" },
        { "endive", "Produce" },
        { "fennel", "Produce" },
        { "fig", "Produce" },
        { "garlic", "Produce" },
        { "ginger", "Produce" },
        { "grape", "Produce" },
        { "grapefruit", "Produce" },
        { "green bean", "Produce" },
        { "green onion", "Produce" },
        { "honeydew", "Produce" },
        { "jalapeno", "Produce" },
        { "kale", "Produce" },
        { "kiwi", "Produce" },
        { "leek", "Produce" },
        { "lemon", "Produce" },
        { "lettuce", "Produce" },
        { "lime", "Produce" },
        { "mango", "Produce" },
        { "mint", "Produce" },
        { "mushroom", "Produce" },
        { "nectarine", "Produce" },
        { "okra", "Produce" },
        { "onion", "Produce" },
        { "orange", "Produce" },
        { "parsley", "Produce" },
        { "parsnip", "Produce" },
        { "peach", "Produce" },
        { "pear", "Produce" },
        { "pea", "Produce" },
        { "pepper", "Produce" },
        { "pineapple", "Produce" },
        { "plantain", "Produce" },
        { "plum", "Produce" },
        { "pomegranate", "Produce" },
        { "potato", "Produce" },
        { "pumpkin", "Produce" },
        { "radish", "Produce" },
        { "raspberry", "Produce" },
        { "red onion", "Produce" },
        { "rhubarb", "Produce" },
        { "romaine", "Produce" },
        { "rosemary", "Produce" },
        { "rutabaga", "Produce" },
        { "sage", "Produce" },
        { "scallion", "Produce" },
        { "shallot", "Produce" },
        { "snap pea", "Produce" },
        { "spinach", "Produce" },
        { "squash", "Produce" },
        { "strawberry", "Produce" },
        { "sweet potato", "Produce" },
        { "swiss chard", "Produce" },
        { "tangerine", "Produce" },
        { "thyme", "Produce" },
        { "tomatillo", "Produce" },
        { "tomato", "Produce" },
        { "turnip", "Produce" },
        { "watercress", "Produce" },
        { "watermelon", "Produce" },
        { "yam", "Produce" },
        { "zucchini", "Produce" },

        // ── Meat & Seafood ──
        { "bacon", "Meat & Seafood" },
        { "beef", "Meat & Seafood" },
        { "bratwurst", "Meat & Seafood" },
        { "chicken", "Meat & Seafood" },
        { "chicken breast", "Meat & Seafood" },
        { "chicken drumstick", "Meat & Seafood" },
        { "chicken thigh", "Meat & Seafood" },
        { "chicken wing", "Meat & Seafood" },
        { "clam", "Meat & Seafood" },
        { "cod", "Meat & Seafood" },
        { "crab", "Meat & Seafood" },
        { "duck", "Meat & Seafood" },
        { "flank steak", "Meat & Seafood" },
        { "ground beef", "Meat & Seafood" },
        { "ground pork", "Meat & Seafood" },
        { "ground turkey", "Meat & Seafood" },
        { "halibut", "Meat & Seafood" },
        { "ham", "Meat & Seafood" },
        { "hot dog", "Meat & Seafood" },
        { "lamb", "Meat & Seafood" },
        { "lobster", "Meat & Seafood" },
        { "mahi mahi", "Meat & Seafood" },
        { "mussel", "Meat & Seafood" },
        { "oyster", "Meat & Seafood" },
        { "pork", "Meat & Seafood" },
        { "pork chop", "Meat & Seafood" },
        { "pork loin", "Meat & Seafood" },
        { "rib", "Meat & Seafood" },
        { "salmon", "Meat & Seafood" },
        { "sardine", "Meat & Seafood" },
        { "sausage", "Meat & Seafood" },
        { "scallop", "Meat & Seafood" },
        { "shrimp", "Meat & Seafood" },
        { "sirloin", "Meat & Seafood" },
        { "steak", "Meat & Seafood" },
        { "swordfish", "Meat & Seafood" },
        { "tilapia", "Meat & Seafood" },
        { "trout", "Meat & Seafood" },
        { "tuna", "Meat & Seafood" },
        { "turkey", "Meat & Seafood" },
        { "veal", "Meat & Seafood" },
        { "venison", "Meat & Seafood" },

        // ── Dairy & Eggs ──
        { "butter", "Dairy & Eggs" },
        { "buttermilk", "Dairy & Eggs" },
        { "cheddar", "Dairy & Eggs" },
        { "cheese", "Dairy & Eggs" },
        { "cottage cheese", "Dairy & Eggs" },
        { "cream", "Dairy & Eggs" },
        { "cream cheese", "Dairy & Eggs" },
        { "egg", "Dairy & Eggs" },
        { "feta", "Dairy & Eggs" },
        { "goat cheese", "Dairy & Eggs" },
        { "gouda", "Dairy & Eggs" },
        { "greek yogurt", "Dairy & Eggs" },
        { "gruyere", "Dairy & Eggs" },
        { "half and half", "Dairy & Eggs" },
        { "heavy cream", "Dairy & Eggs" },
        { "mascarpone", "Dairy & Eggs" },
        { "milk", "Dairy & Eggs" },
        { "monterey jack", "Dairy & Eggs" },
        { "mozzarella", "Dairy & Eggs" },
        { "parmesan", "Dairy & Eggs" },
        { "provolone", "Dairy & Eggs" },
        { "ricotta", "Dairy & Eggs" },
        { "sour cream", "Dairy & Eggs" },
        { "swiss cheese", "Dairy & Eggs" },
        { "whipped cream", "Dairy & Eggs" },
        { "whipping cream", "Dairy & Eggs" },
        { "yogurt", "Dairy & Eggs" },

        // ── Bakery ──
        { "bagel", "Bakery" },
        { "baguette", "Bakery" },
        { "bread", "Bakery" },
        { "brioche", "Bakery" },
        { "bun", "Bakery" },
        { "ciabatta", "Bakery" },
        { "cornbread", "Bakery" },
        { "croissant", "Bakery" },
        { "dinner roll", "Bakery" },
        { "english muffin", "Bakery" },
        { "flatbread", "Bakery" },
        { "hamburger bun", "Bakery" },
        { "hot dog bun", "Bakery" },
        { "naan", "Bakery" },
        { "pita", "Bakery" },
        { "pretzel", "Bakery" },
        { "rye bread", "Bakery" },
        { "sourdough", "Bakery" },
        { "tortilla", "Bakery" },
        { "wheat bread", "Bakery" },
        { "wrap", "Bakery" },

        // ── Frozen ──
        { "frozen fruit", "Frozen" },
        { "frozen meal", "Frozen" },
        { "frozen pizza", "Frozen" },
        { "frozen vegetable", "Frozen" },
        { "frozen waffle", "Frozen" },
        { "ice cream", "Frozen" },
        { "ice pop", "Frozen" },
        { "sorbet", "Frozen" },

        // ── Canned & Jarred ──
        { "anchovy", "Canned & Jarred" },
        { "artichoke heart", "Canned & Jarred" },
        { "black bean", "Canned & Jarred" },
        { "broth", "Canned & Jarred" },
        { "cannellini bean", "Canned & Jarred" },
        { "chicken broth", "Canned & Jarred" },
        { "chickpea", "Canned & Jarred" },
        { "chipotle in adobo", "Canned & Jarred" },
        { "coconut cream", "Canned & Jarred" },
        { "coconut milk", "Canned & Jarred" },
        { "crushed tomato", "Canned & Jarred" },
        { "diced tomato", "Canned & Jarred" },
        { "enchilada sauce", "Canned & Jarred" },
        { "green chile", "Canned & Jarred" },
        { "jam", "Canned & Jarred" },
        { "jelly", "Canned & Jarred" },
        { "kidney bean", "Canned & Jarred" },
        { "lentil", "Canned & Jarred" },
        { "marinara", "Canned & Jarred" },
        { "olive", "Canned & Jarred" },
        { "pinto bean", "Canned & Jarred" },
        { "salsa", "Canned & Jarred" },
        { "sun dried tomato", "Canned & Jarred" },
        { "tomato paste", "Canned & Jarred" },
        { "tomato sauce", "Canned & Jarred" },
        { "tuna can", "Canned & Jarred" },
        { "vegetable broth", "Canned & Jarred" },

        // ── Condiments & Sauces ──
        { "barbecue sauce", "Condiments & Sauces" },
        { "buffalo sauce", "Condiments & Sauces" },
        { "dijon mustard", "Condiments & Sauces" },
        { "fish sauce", "Condiments & Sauces" },
        { "hoisin sauce", "Condiments & Sauces" },
        { "honey", "Condiments & Sauces" },
        { "hot sauce", "Condiments & Sauces" },
        { "ketchup", "Condiments & Sauces" },
        { "maple syrup", "Condiments & Sauces" },
        { "mayonnaise", "Condiments & Sauces" },
        { "mustard", "Condiments & Sauces" },
        { "oyster sauce", "Condiments & Sauces" },
        { "peanut butter", "Condiments & Sauces" },
        { "ranch dressing", "Condiments & Sauces" },
        { "relish", "Condiments & Sauces" },
        { "soy sauce", "Condiments & Sauces" },
        { "sriracha", "Condiments & Sauces" },
        { "steak sauce", "Condiments & Sauces" },
        { "tahini", "Condiments & Sauces" },
        { "teriyaki sauce", "Condiments & Sauces" },
        { "worcestershire sauce", "Condiments & Sauces" },

        // ── Spices & Seasonings ──
        { "allspice", "Spices & Seasonings" },
        { "bay leaf", "Spices & Seasonings" },
        { "black pepper", "Spices & Seasonings" },
        { "cajun seasoning", "Spices & Seasonings" },
        { "cardamom", "Spices & Seasonings" },
        { "cayenne", "Spices & Seasonings" },
        { "celery salt", "Spices & Seasonings" },
        { "chili flake", "Spices & Seasonings" },
        { "chili powder", "Spices & Seasonings" },
        { "cinnamon", "Spices & Seasonings" },
        { "clove", "Spices & Seasonings" },
        { "coriander", "Spices & Seasonings" },
        { "cumin", "Spices & Seasonings" },
        { "curry powder", "Spices & Seasonings" },
        { "garlic powder", "Spices & Seasonings" },
        { "ginger powder", "Spices & Seasonings" },
        { "italian seasoning", "Spices & Seasonings" },
        { "nutmeg", "Spices & Seasonings" },
        { "onion powder", "Spices & Seasonings" },
        { "oregano", "Spices & Seasonings" },
        { "paprika", "Spices & Seasonings" },
        { "red pepper flake", "Spices & Seasonings" },
        { "salt", "Spices & Seasonings" },
        { "smoked paprika", "Spices & Seasonings" },
        { "taco seasoning", "Spices & Seasonings" },
        { "turmeric", "Spices & Seasonings" },
        { "white pepper", "Spices & Seasonings" },

        // ── Baking ──
        { "almond extract", "Baking" },
        { "almond flour", "Baking" },
        { "baking powder", "Baking" },
        { "baking soda", "Baking" },
        { "brown sugar", "Baking" },
        { "cake mix", "Baking" },
        { "chocolate chip", "Baking" },
        { "cocoa powder", "Baking" },
        { "coconut flour", "Baking" },
        { "confectioner sugar", "Baking" },
        { "corn syrup", "Baking" },
        { "cornmeal", "Baking" },
        { "cornstarch", "Baking" },
        { "cream of tartar", "Baking" },
        { "flour", "Baking" },
        { "food coloring", "Baking" },
        { "gelatin", "Baking" },
        { "molasses", "Baking" },
        { "powdered sugar", "Baking" },
        { "shortening", "Baking" },
        { "sugar", "Baking" },
        { "vanilla extract", "Baking" },
        { "yeast", "Baking" },

        // ── Pasta & Grains ──
        { "basmati rice", "Pasta & Grains" },
        { "breadcrumb", "Pasta & Grains" },
        { "brown rice", "Pasta & Grains" },
        { "bulgur", "Pasta & Grains" },
        { "couscous", "Pasta & Grains" },
        { "egg noodle", "Pasta & Grains" },
        { "farro", "Pasta & Grains" },
        { "fettuccine", "Pasta & Grains" },
        { "fusilli", "Pasta & Grains" },
        { "jasmine rice", "Pasta & Grains" },
        { "lasagna noodle", "Pasta & Grains" },
        { "linguine", "Pasta & Grains" },
        { "macaroni", "Pasta & Grains" },
        { "oat", "Pasta & Grains" },
        { "orzo", "Pasta & Grains" },
        { "panko", "Pasta & Grains" },
        { "pasta", "Pasta & Grains" },
        { "penne", "Pasta & Grains" },
        { "polenta", "Pasta & Grains" },
        { "quinoa", "Pasta & Grains" },
        { "ramen noodle", "Pasta & Grains" },
        { "rice", "Pasta & Grains" },
        { "rice noodle", "Pasta & Grains" },
        { "rigatoni", "Pasta & Grains" },
        { "rotini", "Pasta & Grains" },
        { "spaghetti", "Pasta & Grains" },
        { "wild rice", "Pasta & Grains" },

        // ── Snacks ──
        { "almond", "Snacks" },
        { "cashew", "Snacks" },
        { "chip", "Snacks" },
        { "cracker", "Snacks" },
        { "dried fruit", "Snacks" },
        { "granola", "Snacks" },
        { "granola bar", "Snacks" },
        { "hazelnut", "Snacks" },
        { "macadamia", "Snacks" },
        { "pecan", "Snacks" },
        { "pine nut", "Snacks" },
        { "pistachio", "Snacks" },
        { "popcorn", "Snacks" },
        { "pretzel stick", "Snacks" },
        { "pumpkin seed", "Snacks" },
        { "raisin", "Snacks" },
        { "rice cake", "Snacks" },
        { "sesame seed", "Snacks" },
        { "sunflower seed", "Snacks" },
        { "tortilla chip", "Snacks" },
        { "trail mix", "Snacks" },
        { "walnut", "Snacks" },

        // ── Beverages ──
        { "almond milk", "Beverages" },
        { "apple juice", "Beverages" },
        { "beer", "Beverages" },
        { "club soda", "Beverages" },
        { "coconut water", "Beverages" },
        { "coffee", "Beverages" },
        { "energy drink", "Beverages" },
        { "juice", "Beverages" },
        { "lemonade", "Beverages" },
        { "oat milk", "Beverages" },
        { "orange juice", "Beverages" },
        { "soda", "Beverages" },
        { "sparkling water", "Beverages" },
        { "tea", "Beverages" },
        { "tonic water", "Beverages" },
        { "water", "Beverages" },
        { "wine", "Beverages" },

        // ── Deli ──
        { "deli meat", "Deli" },
        { "ham slice", "Deli" },
        { "hummus", "Deli" },
        { "mortadella", "Deli" },
        { "pastrami", "Deli" },
        { "pepperoni", "Deli" },
        { "prosciutto", "Deli" },
        { "rotisserie chicken", "Deli" },
        { "salami", "Deli" },
        { "smoked salmon", "Deli" },
        { "turkey breast", "Deli" },

        // ── Oils & Vinegars ──
        { "apple cider vinegar", "Oils & Vinegars" },
        { "avocado oil", "Oils & Vinegars" },
        { "balsamic vinegar", "Oils & Vinegars" },
        { "canola oil", "Oils & Vinegars" },
        { "coconut oil", "Oils & Vinegars" },
        { "cooking spray", "Oils & Vinegars" },
        { "corn oil", "Oils & Vinegars" },
        { "grapeseed oil", "Oils & Vinegars" },
        { "olive oil", "Oils & Vinegars" },
        { "peanut oil", "Oils & Vinegars" },
        { "red wine vinegar", "Oils & Vinegars" },
        { "rice vinegar", "Oils & Vinegars" },
        { "sesame oil", "Oils & Vinegars" },
        { "vegetable oil", "Oils & Vinegars" },
        { "vinegar", "Oils & Vinegars" },
        { "white vinegar", "Oils & Vinegars" },
        { "white wine vinegar", "Oils & Vinegars" },
    };
}
