/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as ShoppingListsRouteImport } from './routes/shopping-lists'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as MealPlanRouteImport } from './routes/meal-plan'
import { Route as FilterDemoRouteImport } from './routes/filter-demo'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as ShoppingListsIndexRouteImport } from './routes/shopping-lists.index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as MealPlanIndexRouteImport } from './routes/meal-plan.index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as StoresIdRouteImport } from './routes/stores.$id'
import { Route as ShoppingListsIdRouteImport } from './routes/shopping-lists.$id'
import { Route as RecipesNewRouteImport } from './routes/recipes.new'
import { Route as RecipesImportCmtRouteImport } from './routes/recipes.import-cmt'
import { Route as RecipesImportRouteImport } from './routes/recipes.import'
import { Route as RecipesIdRouteImport } from './routes/recipes.$id'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as StoresIdIndexRouteImport } from './routes/stores.$id.index'
import { Route as ShoppingListsIdIndexRouteImport } from './routes/shopping-lists.$id.index'
import { Route as RecipesIdIndexRouteImport } from './routes/recipes.$id.index'
import { Route as CollectionsIdIndexRouteImport } from './routes/collections.$id.index'
import { Route as ShoppingListsIdEditRouteImport } from './routes/shopping-lists.$id.edit'
import { Route as RecipesIdEditRouteImport } from './routes/recipes.$id.edit'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListsRoute = ShoppingListsRouteImport.update({
  id: '/shopping-lists',
  path: '/shopping-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlanRoute = MealPlanRouteImport.update({
  id: '/meal-plan',
  path: '/meal-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const FilterDemoRoute = FilterDemoRouteImport.update({
  id: '/filter-demo',
  path: '/filter-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoresRoute,
} as any)
const ShoppingListsIndexRoute = ShoppingListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShoppingListsRoute,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecipesRoute,
} as any)
const MealPlanIndexRoute = MealPlanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MealPlanRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const StoresIdRoute = StoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoresRoute,
} as any)
const ShoppingListsIdRoute = ShoppingListsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShoppingListsRoute,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RecipesRoute,
} as any)
const RecipesImportCmtRoute = RecipesImportCmtRouteImport.update({
  id: '/import-cmt',
  path: '/import-cmt',
  getParentRoute: () => RecipesRoute,
} as any)
const RecipesImportRoute = RecipesImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => RecipesRoute,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecipesRoute,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollectionsRoute,
} as any)
const StoresIdIndexRoute = StoresIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoresIdRoute,
} as any)
const ShoppingListsIdIndexRoute = ShoppingListsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShoppingListsIdRoute,
} as any)
const RecipesIdIndexRoute = RecipesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecipesIdRoute,
} as any)
const CollectionsIdIndexRoute = CollectionsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsIdRoute,
} as any)
const ShoppingListsIdEditRoute = ShoppingListsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ShoppingListsIdRoute,
} as any)
const RecipesIdEditRoute = RecipesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RecipesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/components': typeof ComponentsRoute
  '/filter-demo': typeof FilterDemoRoute
  '/meal-plan': typeof MealPlanRouteWithChildren
  '/recipes': typeof RecipesRouteWithChildren
  '/shopping-lists': typeof ShoppingListsRouteWithChildren
  '/stores': typeof StoresRouteWithChildren
  '/collections/$id': typeof CollectionsIdRouteWithChildren
  '/recipes/$id': typeof RecipesIdRouteWithChildren
  '/recipes/import': typeof RecipesImportRoute
  '/recipes/import-cmt': typeof RecipesImportCmtRoute
  '/recipes/new': typeof RecipesNewRoute
  '/shopping-lists/$id': typeof ShoppingListsIdRouteWithChildren
  '/stores/$id': typeof StoresIdRouteWithChildren
  '/collections/': typeof CollectionsIndexRoute
  '/meal-plan/': typeof MealPlanIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/shopping-lists/': typeof ShoppingListsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
  '/shopping-lists/$id/edit': typeof ShoppingListsIdEditRoute
  '/collections/$id/': typeof CollectionsIdIndexRoute
  '/recipes/$id/': typeof RecipesIdIndexRoute
  '/shopping-lists/$id/': typeof ShoppingListsIdIndexRoute
  '/stores/$id/': typeof StoresIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/filter-demo': typeof FilterDemoRoute
  '/recipes/import': typeof RecipesImportRoute
  '/recipes/import-cmt': typeof RecipesImportCmtRoute
  '/recipes/new': typeof RecipesNewRoute
  '/collections': typeof CollectionsIndexRoute
  '/meal-plan': typeof MealPlanIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/shopping-lists': typeof ShoppingListsIndexRoute
  '/stores': typeof StoresIndexRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
  '/shopping-lists/$id/edit': typeof ShoppingListsIdEditRoute
  '/collections/$id': typeof CollectionsIdIndexRoute
  '/recipes/$id': typeof RecipesIdIndexRoute
  '/shopping-lists/$id': typeof ShoppingListsIdIndexRoute
  '/stores/$id': typeof StoresIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/components': typeof ComponentsRoute
  '/filter-demo': typeof FilterDemoRoute
  '/meal-plan': typeof MealPlanRouteWithChildren
  '/recipes': typeof RecipesRouteWithChildren
  '/shopping-lists': typeof ShoppingListsRouteWithChildren
  '/stores': typeof StoresRouteWithChildren
  '/collections/$id': typeof CollectionsIdRouteWithChildren
  '/recipes/$id': typeof RecipesIdRouteWithChildren
  '/recipes/import': typeof RecipesImportRoute
  '/recipes/import-cmt': typeof RecipesImportCmtRoute
  '/recipes/new': typeof RecipesNewRoute
  '/shopping-lists/$id': typeof ShoppingListsIdRouteWithChildren
  '/stores/$id': typeof StoresIdRouteWithChildren
  '/collections/': typeof CollectionsIndexRoute
  '/meal-plan/': typeof MealPlanIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/shopping-lists/': typeof ShoppingListsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
  '/shopping-lists/$id/edit': typeof ShoppingListsIdEditRoute
  '/collections/$id/': typeof CollectionsIdIndexRoute
  '/recipes/$id/': typeof RecipesIdIndexRoute
  '/shopping-lists/$id/': typeof ShoppingListsIdIndexRoute
  '/stores/$id/': typeof StoresIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/components'
    | '/filter-demo'
    | '/meal-plan'
    | '/recipes'
    | '/shopping-lists'
    | '/stores'
    | '/collections/$id'
    | '/recipes/$id'
    | '/recipes/import'
    | '/recipes/import-cmt'
    | '/recipes/new'
    | '/shopping-lists/$id'
    | '/stores/$id'
    | '/collections/'
    | '/meal-plan/'
    | '/recipes/'
    | '/shopping-lists/'
    | '/stores/'
    | '/recipes/$id/edit'
    | '/shopping-lists/$id/edit'
    | '/collections/$id/'
    | '/recipes/$id/'
    | '/shopping-lists/$id/'
    | '/stores/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/filter-demo'
    | '/recipes/import'
    | '/recipes/import-cmt'
    | '/recipes/new'
    | '/collections'
    | '/meal-plan'
    | '/recipes'
    | '/shopping-lists'
    | '/stores'
    | '/recipes/$id/edit'
    | '/shopping-lists/$id/edit'
    | '/collections/$id'
    | '/recipes/$id'
    | '/shopping-lists/$id'
    | '/stores/$id'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/components'
    | '/filter-demo'
    | '/meal-plan'
    | '/recipes'
    | '/shopping-lists'
    | '/stores'
    | '/collections/$id'
    | '/recipes/$id'
    | '/recipes/import'
    | '/recipes/import-cmt'
    | '/recipes/new'
    | '/shopping-lists/$id'
    | '/stores/$id'
    | '/collections/'
    | '/meal-plan/'
    | '/recipes/'
    | '/shopping-lists/'
    | '/stores/'
    | '/recipes/$id/edit'
    | '/shopping-lists/$id/edit'
    | '/collections/$id/'
    | '/recipes/$id/'
    | '/shopping-lists/$id/'
    | '/stores/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ComponentsRoute: typeof ComponentsRoute
  FilterDemoRoute: typeof FilterDemoRoute
  MealPlanRoute: typeof MealPlanRouteWithChildren
  RecipesRoute: typeof RecipesRouteWithChildren
  ShoppingListsRoute: typeof ShoppingListsRouteWithChildren
  StoresRoute: typeof StoresRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-lists': {
      id: '/shopping-lists'
      path: '/shopping-lists'
      fullPath: '/shopping-lists'
      preLoaderRoute: typeof ShoppingListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plan': {
      id: '/meal-plan'
      path: '/meal-plan'
      fullPath: '/meal-plan'
      preLoaderRoute: typeof MealPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filter-demo': {
      id: '/filter-demo'
      path: '/filter-demo'
      fullPath: '/filter-demo'
      preLoaderRoute: typeof FilterDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof StoresRoute
    }
    '/shopping-lists/': {
      id: '/shopping-lists/'
      path: '/'
      fullPath: '/shopping-lists/'
      preLoaderRoute: typeof ShoppingListsIndexRouteImport
      parentRoute: typeof ShoppingListsRoute
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/meal-plan/': {
      id: '/meal-plan/'
      path: '/'
      fullPath: '/meal-plan/'
      preLoaderRoute: typeof MealPlanIndexRouteImport
      parentRoute: typeof MealPlanRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/stores/$id': {
      id: '/stores/$id'
      path: '/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof StoresIdRouteImport
      parentRoute: typeof StoresRoute
    }
    '/shopping-lists/$id': {
      id: '/shopping-lists/$id'
      path: '/$id'
      fullPath: '/shopping-lists/$id'
      preLoaderRoute: typeof ShoppingListsIdRouteImport
      parentRoute: typeof ShoppingListsRoute
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/recipes/import-cmt': {
      id: '/recipes/import-cmt'
      path: '/import-cmt'
      fullPath: '/recipes/import-cmt'
      preLoaderRoute: typeof RecipesImportCmtRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/recipes/import': {
      id: '/recipes/import'
      path: '/import'
      fullPath: '/recipes/import'
      preLoaderRoute: typeof RecipesImportRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/stores/$id/': {
      id: '/stores/$id/'
      path: '/'
      fullPath: '/stores/$id/'
      preLoaderRoute: typeof StoresIdIndexRouteImport
      parentRoute: typeof StoresIdRoute
    }
    '/shopping-lists/$id/': {
      id: '/shopping-lists/$id/'
      path: '/'
      fullPath: '/shopping-lists/$id/'
      preLoaderRoute: typeof ShoppingListsIdIndexRouteImport
      parentRoute: typeof ShoppingListsIdRoute
    }
    '/recipes/$id/': {
      id: '/recipes/$id/'
      path: '/'
      fullPath: '/recipes/$id/'
      preLoaderRoute: typeof RecipesIdIndexRouteImport
      parentRoute: typeof RecipesIdRoute
    }
    '/collections/$id/': {
      id: '/collections/$id/'
      path: '/'
      fullPath: '/collections/$id/'
      preLoaderRoute: typeof CollectionsIdIndexRouteImport
      parentRoute: typeof CollectionsIdRoute
    }
    '/shopping-lists/$id/edit': {
      id: '/shopping-lists/$id/edit'
      path: '/edit'
      fullPath: '/shopping-lists/$id/edit'
      preLoaderRoute: typeof ShoppingListsIdEditRouteImport
      parentRoute: typeof ShoppingListsIdRoute
    }
    '/recipes/$id/edit': {
      id: '/recipes/$id/edit'
      path: '/edit'
      fullPath: '/recipes/$id/edit'
      preLoaderRoute: typeof RecipesIdEditRouteImport
      parentRoute: typeof RecipesIdRoute
    }
  }
}

interface CollectionsIdRouteChildren {
  CollectionsIdIndexRoute: typeof CollectionsIdIndexRoute
}

const CollectionsIdRouteChildren: CollectionsIdRouteChildren = {
  CollectionsIdIndexRoute: CollectionsIdIndexRoute,
}

const CollectionsIdRouteWithChildren = CollectionsIdRoute._addFileChildren(
  CollectionsIdRouteChildren,
)

interface CollectionsRouteChildren {
  CollectionsIdRoute: typeof CollectionsIdRouteWithChildren
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsIdRoute: CollectionsIdRouteWithChildren,
  CollectionsIndexRoute: CollectionsIndexRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface MealPlanRouteChildren {
  MealPlanIndexRoute: typeof MealPlanIndexRoute
}

const MealPlanRouteChildren: MealPlanRouteChildren = {
  MealPlanIndexRoute: MealPlanIndexRoute,
}

const MealPlanRouteWithChildren = MealPlanRoute._addFileChildren(
  MealPlanRouteChildren,
)

interface RecipesIdRouteChildren {
  RecipesIdEditRoute: typeof RecipesIdEditRoute
  RecipesIdIndexRoute: typeof RecipesIdIndexRoute
}

const RecipesIdRouteChildren: RecipesIdRouteChildren = {
  RecipesIdEditRoute: RecipesIdEditRoute,
  RecipesIdIndexRoute: RecipesIdIndexRoute,
}

const RecipesIdRouteWithChildren = RecipesIdRoute._addFileChildren(
  RecipesIdRouteChildren,
)

interface RecipesRouteChildren {
  RecipesIdRoute: typeof RecipesIdRouteWithChildren
  RecipesImportRoute: typeof RecipesImportRoute
  RecipesImportCmtRoute: typeof RecipesImportCmtRoute
  RecipesNewRoute: typeof RecipesNewRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

const RecipesRouteChildren: RecipesRouteChildren = {
  RecipesIdRoute: RecipesIdRouteWithChildren,
  RecipesImportRoute: RecipesImportRoute,
  RecipesImportCmtRoute: RecipesImportCmtRoute,
  RecipesNewRoute: RecipesNewRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}

const RecipesRouteWithChildren =
  RecipesRoute._addFileChildren(RecipesRouteChildren)

interface ShoppingListsIdRouteChildren {
  ShoppingListsIdEditRoute: typeof ShoppingListsIdEditRoute
  ShoppingListsIdIndexRoute: typeof ShoppingListsIdIndexRoute
}

const ShoppingListsIdRouteChildren: ShoppingListsIdRouteChildren = {
  ShoppingListsIdEditRoute: ShoppingListsIdEditRoute,
  ShoppingListsIdIndexRoute: ShoppingListsIdIndexRoute,
}

const ShoppingListsIdRouteWithChildren = ShoppingListsIdRoute._addFileChildren(
  ShoppingListsIdRouteChildren,
)

interface ShoppingListsRouteChildren {
  ShoppingListsIdRoute: typeof ShoppingListsIdRouteWithChildren
  ShoppingListsIndexRoute: typeof ShoppingListsIndexRoute
}

const ShoppingListsRouteChildren: ShoppingListsRouteChildren = {
  ShoppingListsIdRoute: ShoppingListsIdRouteWithChildren,
  ShoppingListsIndexRoute: ShoppingListsIndexRoute,
}

const ShoppingListsRouteWithChildren = ShoppingListsRoute._addFileChildren(
  ShoppingListsRouteChildren,
)

interface StoresIdRouteChildren {
  StoresIdIndexRoute: typeof StoresIdIndexRoute
}

const StoresIdRouteChildren: StoresIdRouteChildren = {
  StoresIdIndexRoute: StoresIdIndexRoute,
}

const StoresIdRouteWithChildren = StoresIdRoute._addFileChildren(
  StoresIdRouteChildren,
)

interface StoresRouteChildren {
  StoresIdRoute: typeof StoresIdRouteWithChildren
  StoresIndexRoute: typeof StoresIndexRoute
}

const StoresRouteChildren: StoresRouteChildren = {
  StoresIdRoute: StoresIdRouteWithChildren,
  StoresIndexRoute: StoresIndexRoute,
}

const StoresRouteWithChildren =
  StoresRoute._addFileChildren(StoresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ComponentsRoute: ComponentsRoute,
  FilterDemoRoute: FilterDemoRoute,
  MealPlanRoute: MealPlanRouteWithChildren,
  RecipesRoute: RecipesRouteWithChildren,
  ShoppingListsRoute: ShoppingListsRouteWithChildren,
  StoresRoute: StoresRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
